### ISSUE TITLE
uhr.ino

### ISSUE THREAD

**Issue by FROGGS** [MueThoS76/Rheinturm#1]
https://github.com/MueThoS76/Rheinturm/blob/fffa25219b75d17d1ad934f5279863e254a9254b/uhr.ino#L11-L12
Hier würde ich ein Makro schreiben, damit die Gültigkeitsprüfung auf die erhaltene Zeitinfo deutlich wird.
```cpp
#define TIMEINFO_INVALID (timeinfo.tm_year <= (2016 - 1900))
```
Und dann:
```cpp
} while (((millis() - start) <= (1000 * sec)) && TIMEINFO_INVALID);
if (TIMEINFO_INVALID) return false;  // the NTP call was not successful
```
-----------------------------

https://github.com/MueThoS76/Rheinturm/blob/fffa25219b75d17d1ad934f5279863e254a9254b/uhr.ino#L19
Das würde ich explizit casten:
```cpp
sekunden.zehner = (unsigned short)(timeinfo.tm_sec / 10);
```

**Comment by MueThoS76** [comment]
Der erste Teil ist umgesetzt.
Beim zweiten habe ich zwar den code gekürzt ich verstehe nicht warum ich das unsigned short rein machen soll.

aktuell ist es so:
```
sekunden.einer  = timeinfo.tm_sec  % 10;
sekunden.zehner = timeinfo.tm_sec  / 10;
minuten.einer   = timeinfo.tm_min  % 10;
minuten.zehner  = timeinfo.tm_min  / 10;
stunden.einer   = timeinfo.tm_hour % 10;
stunden.zehner  = timeinfo.tm_hour / 10;
```
Und das macht auch was es soll.

https://github.com/MueThoS76/Rheinturm/blob/0af6f29a3796d35ff9f0dfd95bea268445ed1c26/Rheinturm.ino#L22-L25
Ich weiß nicht mehr warum ich da das byte gemacht habe

**Comment by FROGGS** [comment]
Ein expliziter Cast ist besser als ein impliziter, weil du dann im Code siehst was passiert. Sonst siehst du ja garnicht dass er "abrundet".

**Comment by MueThoS76** [comment]
Ich habe es eingebaut
