### ISSUE TITLE
ledstrip.ino

### ISSUE THREAD

**Issue by FROGGS** [MueThoS76/Rheinturm#2]
https://github.com/MueThoS76/Rheinturm/blob/master/ledstrip.ino#L3
Hier würde ich definitiv mit Variablen arbeiten:

```cpp
for (int i = LED_SEKUNDEN_EINER_MIN; i <= LED_SEKUNDEN_EINER_MAX; i++) {
    if (i - LED_SEKUNDEN_EINER_MIN < sekunden.einer) {
```
Das klappt dann bei allen anderen LEDs auch so.

------------------------------
https://github.com/MueThoS76/Rheinturm/blob/master/ledstrip.ino#L5
Hier solltest du zentral die Farben speichern:
```cpp
// Im Hauptprogramm, ACHTUNG: ich weiß nicht ob `int` hier richtig ist.
int LED_ON  = PIXELS_CLOCK.Color(100,80,0);
int LED_OFF = PIXELS_CLOCK.Color(0,0,0);

// In ledstrip.ino
if (i - LED_SEKUNDEN_EINER_MIN < sekunden.einer) {
  PIXELS_CLOCK.setPixelColor(i, LED_ON);
} else {
  PIXELS_CLOCK.setPixelColor(i, LED_OFF);
}
```

**Comment by MueThoS76** [comment]
Beides wurde umgesetzt
